draw_config:
  key_w: 60
  key_h: 60
  split_gap: 10.0
  combo_w: 28
  combo_h: 28
  key_rx: 6.0
  key_ry: 6.0
  dark_mode: true
  n_columns: 1
  separate_combo_diagrams: false
  combo_diagrams_scale: 3
  inner_pad_w: 2.0
  inner_pad_h: 2.0
  outer_pad_w: 30.0
  outer_pad_h: 60.0
  line_spacing: 1.2
  arc_radius: 6.0
  append_colon_to_layer_header: true
  small_pad: 2.0
  legend_rel_x: 0.0
  legend_rel_y: 0.0
  draw_key_sides: false
  key_side_pars:
    rel_x: 0.0
    rel_y: 4.0
    rel_w: 12.0
    rel_h: 12.0
    rx: 4.0
    ry: 4.0
  svg_extra_style: |-
    /* Base keymap styling using Catppuccin Mocha theme */
    svg.keymap {
        font-family: SFMono-Regular, Consolas, Liberation Mono, Menlo, monospace;
        font-size: 14px;
        font-kerning: normal;
        text-rendering: optimizeLegibility;
        fill: #cdd6f4;
        background-color: #1e1e2e;
    }

    rect.key {
        fill: #313244;
    }

    rect.key, rect.combo {
        stroke: #45475a;
        stroke-width: 1;
    }

    rect.side {
        filter: brightness(90%);
    }

    rect.combo, rect.combo-separate {
        fill: #74c7ec;
    }

    rect.held, rect.combo.held {
        fill: #f38ba8;
    }

    rect.ghost, rect.combo.ghost {
        stroke-dasharray: 4, 4;
        stroke-width: 2;
    }

    text {
        text-anchor: middle;
        dominant-baseline: middle;
        fill: #cdd6f4;
    }

    text.label {
        font-weight: bold;
        text-anchor: start;
        stroke: #11111b;
        stroke-width: 4;
        paint-order: stroke;
    }

    text.footer {
        text-anchor: end;
        dominant-baseline: auto;
        stroke: #11111b;
        stroke-width: 4;
        paint-order: stroke;
    }

    text.combo, text.hold, text.shifted, text.left, text.right {
        font-size: 11px;
    }

    text.hold {
        text-anchor: middle;
        dominant-baseline: auto;
    }

    text.shifted {
        text-anchor: middle;
        dominant-baseline: hanging;
    }

    text.left {
        text-anchor: start;
    }

    text.right {
        text-anchor: end;
    }

    text.layer-activator {
        text-decoration: underline;
    }

    text.combo.hold, text.combo.shifted, text.combo.left, text.combo.right {
        font-size: 8px;
    }

    text.trans {
        fill: #7f849c;
    }

    path.combo {
        stroke-width: 1;
        stroke: #9399b2;
        fill: none;
    }

    svg path {
        fill: inherit;
    }

    .icon-tabler > path {
        fill: inherit;
        stroke: inherit;
        stroke-width: 2;
    }
    .icon-tabler > path[stroke="none"][fill="none"] {
        visibility: hidden;
    }
    rect.combo{
        fill: #1f3d7a;
    }
    rect.combo-separate{
       fill: #1f3d7a;
       x: 60;
       width: 60px;
       height: 60px;
    }
    text.combo-separate {
       transform: translateX(90px) translatey(4px);
    }

    use.phosphor\:regular\/mouse-right-click,
    use.phosphor\:regular\/mouse-left-click{
      transform: scale(1.6)
    }

    use.phosphor\:regular\/arrow-fat-up,
    use.phosphor\:regular\/command,
    use.phosphor\:regular\/option,
    use.phosphor\:regular\/mouse-right-click,
    use.phosphor\:regular\/mouse-left-click,
    use.phosphor\:regular\/backspace,
    use.phosphor\:regular\/key-return,
    use.phosphor\:regular\/control {
      color: #cdd6f4
    }
  footer_text: <a href="https://github.com/MuhametSmaili/zmk-config">MuhametSmaili/zmk-config</a>
  shrink_wide_legends: 7
  style_layer_activators: true
  glyph_tap_size: 14
  glyph_hold_size: 12
  glyph_shifted_size: 10
  glyphs: {}
parse_config:
  preprocess: true
  skip_binding_parsing: false
  raw_binding_map:
    '&sys_reset': Reset
    '&bootloader': Boot
    '&caps_word': Caps Word
    '&ind_bat': Show Batt
    '&ind_con': Show Conn
    '&studio_unlock': Studio Unlock
    '&soft_off': Soft Off
    '&out OUT_USB': Out USB
    '&out OUT_BLE': Out BT
    '&tof MSE': Toggle MSE
    '&tof 4': Toggle MSE
    '&bt BT_SEL 0': BT 1
    '&bt BT_SEL 1': BT 2
    '&bt BT_SEL 2': BT 3
    '&bt BT_SEL 3': BT 4
    '&bt BT_SEL 4': BT 5
    '&bt BT_CLR_ALL': BT Clear All
    '&bt BT_CLR': BT Clear
    '&mmv MOVE_UP': Mouse ↑
    '&mmv MOVE_DOWN': Mouse ↓
    '&mmv MOVE_LEFT': Mouse ←
    '&mmv MOVE_RIGHT': Mouse →
    '&msc SCRL_UP': Scroll ↑
    '&msc SCRL_DOWN': Scroll ↓
    '&msc SCRL_LEFT': Scroll ←
    '&msc SCRL_RIGHT': Scroll →
    '&mkp LCLK': $$phosphor:regular/mouse-left-click$$
    '&mkp RCLK': $$phosphor:regular/mouse-right-click$$
    '&mkp MCLK': Middle Click
    '&mkp MB4': Back Click
    '&mkp MB5': Forward Click
  sticky_label: sticky
  toggle_label: toggle
  tap_toggle_label: tap-toggle
  trans_legend:
    t: ▽
    type: trans
  layer_legend_map: {}
  mark_alternate_layer_activators: false
  modifier_fn_map:
    left_ctrl: $$phosphor:regular/control$$
    right_ctrl: $$phosphor:regular/control$$
    left_shift: $$phosphor:regular/arrow-fat-up$$
    right_shift: $$phosphor:regular/arrow-fat-up$$
    left_alt: $$phosphor:regular/option$$
    right_alt: $$phosphor:regular/option$$
    left_gui: $$phosphor:regular/command$$
    right_gui: $$phosphor:regular/command$$
    keycode_combiner: '{mods}+{key}'
    mod_combiner: '{mod_1}+{mod_2}'
    special_combinations:
      left_ctrl+left_alt+left_gui+left_shift: Hyper
      left_ctrl+left_alt+left_shift: Meh
  qmk_remove_keycode_prefix:
  - KC_
  qmk_keycode_map:
    XXXXXXX: ''
    'NO': ''
    MINUS: '-'
    MINS: '-'
    EQUAL: '='
    EQL: '='
    LEFT_BRACKET: '['
    LBRC: '['
    RIGHT_BRACKET: ']'
    RBRC: ']'
    BACKSLASH: \
    BSLS: \
    NONUS_HASH: '#'
    NUHS: '#'
    SEMICOLON: ;
    SCLN: ;
    QUOTE: ''''
    QUOT: ''''
    GRAVE: '`'
    GRV: '`'
    COMMA: ','
    COMM: ','
    DOT: .
    SLASH: /
    SLSH: /
    TILDE: '~'
    TILD: '~'
    EXCLAIM: '!'
    EXLM: '!'
    AT: '@'
    HASH: '#'
    DOLLAR: $
    DLR: $
    PERCENT: '%'
    PERC: '%'
    CIRCUMFLEX: ^
    CIRC: ^
    AMPERSAND: '&'
    AMPR: '&'
    ASTERISK: '*'
    ASTR: '*'
    LEFT_PAREN: (
    LPRN: (
    RIGHT_PAREN: )
    RPRN: )
    UNDERSCORE: _
    UNDS: _
    PLUS: +
    LEFT_CURLY_BRACE: '{'
    LCBR: '{'
    RIGHT_CURLY_BRACE: '}'
    RCBR: '}'
    PIPE: '|'
    COLON: ':'
    COLN: ':'
    DOUBLE_QUOTE: '"'
    DQUO: '"'
    DQT: '"'
    LEFT_ANGLE_BRACKET: <
    LABK: <
    LT: <
    RIGHT_ANGLE_BRACKET: '>'
    RABK: '>'
    GT: '>'
    QUESTION: '?'
    QUES: '?'
  zmk_remove_keycode_prefix: []
  zmk_keycode_map:
    C_MUTE: $$mdi:volume-off$$
    C_PP: $$mdi:play-pause$$
    C_VOL_UP: $$mdi:volume-high$$
    C_VOL_DN: $$mdi:volume-medium$$
    C_NEXT: $$mdi:skip-forward$$
    C_PREV: $$mdi:skip-backward$$
    BT: $$mdi:bluetooth$$
    tof: Toggle
    LCTRL: $$phosphor:regular/control$$
    RCTRL: $$phosphor:regular/control$$
    LALT: $$phosphor:regular/option$$
    RALT: $$phosphor:regular/option$$
    LGUI: $$phosphor:regular/command$$
    RGUI: $$phosphor:regular/command$$
    LSHFT: $$phosphor:regular/arrow-fat-up$$
    RSHFT: $$phosphor:regular/arrow-fat-up$$
    ESC: Esc
    SPACE: $$mdi:keyboard-space$$
    BSPC: $$phosphor:regular/backspace$$
    RET: ⏎
    ENTER: ⏎
    TAB: ↹
    DEL: ⌦
    DELETE: Delete
    PG_UP: PgUp
    PG_DN: PgDwn
    INS: Insert
    HOME: Home
    END: End
    PSCRN: Print Scrn
    LG(C): Copy
    LG(X): Cut
    LG(V): Paste
    UP: ↑
    DOWN: ↓
    LEFT: ←
    RIGHT: →
    EXCLAMATION: '!'
    EXCL: '!'
    AT_SIGN: '@'
    AT: '@'
    HASH: '#'
    POUND: '#'
    DOLLAR: $
    DLLR: $
    PERCENT: '%'
    PRCNT: '%'
    CARET: ^
    AMPERSAND: '&'
    AMPS: '&'
    ASTERISK: '*'
    ASTRK: '*'
    STAR: '*'
    LEFT_PARENTHESIS: (
    LPAR: (
    RIGHT_PARENTHESIS: )
    RPAR: )
    EQUAL: '='
    PLUS: +
    MINUS: '-'
    UNDERSCORE: _
    UNDER: _
    SLASH: /
    FSLH: /
    QUESTION: '?'
    QMARK: '?'
    BACKSLASH: \
    BSLH: \
    PIPE: '|'
    NON_US_BACKSLASH: \
    PIPE2: '|'
    NON_US_BSLH: '|'
    SEMICOLON: ;
    SEMI: ;
    COLON: ':'
    SINGLE_QUOTE: ''''
    SQT: ''''
    APOSTROPHE: ''''
    APOS: ''''
    DOUBLE_QUOTES: '"'
    DQT: '"'
    COMMA: ','
    LESS_THAN: <
    LT: <
    PERIOD: .
    DOT: .
    GREATER_THAN: '>'
    GT: '>'
    LEFT_BRACKET: '['
    LBKT: '['
    LEFT_BRACE: '{'
    LBRC: '{'
    RIGHT_BRACKET: ']'
    RBKT: ']'
    RIGHT_BRACE: '}'
    RBRC: '}'
    GRAVE: '`'
    TILDE: '~'
    NON_US_HASH: '#'
    NUHS: '#'
    TILDE2: '~'
  zmk_combos:
    combo_scroll_up:
      a: top
      o: 0.4
    combo_scroll_down:
      a: bottom
      o: 0.2
    combo_caps_word:
      draw_separate: true
    combo_enter:
      draw_separate: true
    combo_cut:
      a: bottom
      o: 0.2
    combo_bt_clear_all:
      a: bottom
      o: 1.3
    combo_indbat:
      a: top
      o: 1
    combo_indcon:
      a: top
      o: 0.5
  zmk_preamble: '#define KEYMAP_DRAWER'
  zmk_additional_includes: []
